### ISSUE TITLE
Add a search bar to the roles selection in the mobile view

### ISSUE THREAD

**Issue by anshulagx** [catoverse/yellowjobs-frontend#26]
The search bar for roles selection already works for desktop view. Implement it in mobile view as well.

**Comment by VarunSAthreya** [comment]
The search bar must be added here in mobile view?

![Capture](https://user-images.githubusercontent.com/64711780/129483842-fba702dd-5c10-4842-a71e-207870630b1c.PNG)

**Comment by anshulagx** [comment]
Hey, we decided to scrape this issue because we feel that adding a search bar will clutter the UI. 
Thanks
