### ISSUE TITLE
Add a fresher filter

### ISSUE THREAD

**Issue by anshulagx** [catoverse/yellowjobs-frontend#28]
Add a checkbox for "freshers" along with the already existing filters like "fulltime", "freelance" etc

**Comment by meamitacharya** [comment]
Can you explain this issue in detail @anshulagx :D

**Comment by anshulagx** [comment]
Yaa sure!
![Capture](https://user-images.githubusercontent.com/26869731/129468775-d8361d79-dc1c-4910-9bea-a327cfad10a8.JPG)
So currently we have 4 filters. Freelance, part time, full time and internship. 
Many users requested us to add a fifth one to show only roles for freshers/ one without experience.

In the frontend we just have to add a checkbox similar to the ones existing here
https://github.com/catoverse/yellowjobs-frontend/blob/c5855350a8321f0cc8351392ab3413d666153c33/components/job-categories.jsx

This is the corresponding backend issue 
https://github.com/catoverse/yellowjobs-backend-service/issues/5

**Comment by meamitacharya** [comment]
Yeah sure. You can assign this issue to me and I will look forward to it.
